### ISSUE TITLE
Cursorsize

### ISSUE THREAD

**Issue by MarcSchmer** [EliasBF/angular-typing-animation#1]
Hi,

thanks for your effort.
Could you also give the possibility to adjust the cursor size?

Thanks a lot and kind regards
Marc

**Comment by gitsmith123** [comment]
Hi,

Is it possible to use multiple words and display them in a single line one after the other with blinking cursor. I see that, as of now it displays all the text at the same time. But I am expecting it to show up one after the other in the same place that too in rotation... 

I'm looking something like this: https://codekraft.it/demos/angular-typed/

Please help.. I am a beginner in Angular..

Thanks a lot in advance! 
Smith

**Comment by eliashbf** [comment]
Hi @MarcSchmer 

The cursor has by default the size of the text element to which you apply the animation, unless you define the styles embedded in the element or after the creation of the directive.

If you want to add a different size you can use the class ```.typed-cursor``` in your styles or do it dynamically by changing the value of the cursor font size:

``` css
span.typed-cursor {
    font-size: 24px;
}
```

I hope it helps you

**Comment by eliashbf** [comment]
Hi @gitsmith123 

This Angular directive is based on the library [Typed.js](https://mattboldt.com/demos/typed-js/) in the future all its features will be implemented and will include what you are looking for, for now I suggest you use that library directly from an import in your components and through the decorator ```@ViewChild``` captures the text elements and apply the animation:

* custom.component.html
``` html
<span #text></span>
```

* custom.component.ts
``` typescript
import Typed from 'typed.js'
...

@Component({
  selector: 'custom',
  templateUrl: './custom.component.html'
})
export class CustomComponent implements OnInit {
    @ViewChild('text', { read: ElementRef }) text: ElementRef

    ngOnInit () {
        let textEl = this.text.nativeElement
        let typed = new Typed(textEl, {
            strings: ['First sentence', 'Second sentence', 'More sentences...'],
            typeSpeed: 40
        })
    }
    ...
}
```

You can see more examples of how to use the library from here:
[https://mattboldt.com/demos/typed-js/](https://mattboldt.com/demos/typed-js/)

regards.
